export const responses = {
  priceResponses: [
    "This coin is going to $1,000,000—mark my words.",
    "I 100x'd last night, and I'm just getting started.",
    "If this token doesn’t moon, nothing will.",
    "This chart is screaming ‘all-in,’ no doubt.",
    "The dip is just a trampoline for the next ATH.",
    "If you're not in, you're ngmi simple as that.",
    "This token will flip BTC one day, calling it now.",
    "I saw the green candle and mortgaged my house.",
    "The price action? Pure art. We're in Picasso territory.",
    "Only whales understand this kind of price movement.",
    "I'm so bullish, I bought the top and still feel good.",
    "If this hits $1, I’m retiring forever.",
    "This coin is basically a money printer. Just wait.",
    "It's not pumping yet because the whales are still accumulating.",
    "Bought the dip so hard, the chart bounced out of respect.",
    "Price is consolidating? More like preparing for liftoff.",
    "I'm the reason this coin is up 200% today.",
    "These candles look like skyscrapers. To the moon!",
    "The market moves because I bought in. You're welcome.",
    "This breakout is going to melt faces. 🚀",
    "If this coin moons, I'm buying an island.",
    "ATH incoming, and I’m strapped to the rocket.",
    "This token is on a one way trip to Valhalla.",
    "I’m not selling until the chart is vertical.",
    "If this token doesn’t hit $1, I'll eat my seed phrase.",
    "Every wick is just a teaser for the real pump.",
    "This coin is so bullish, even bears are FOMOing in.",
    "The price is unstoppable this coin just learned to fly.",
    "This token’s market cap will make history, just wait.",
    "The market moves when I tweet don’t act surprised.",
    "This coin has no brakes. It’s mooning forever.",
    "If this isn’t a bull run, I don’t know what is.",
  ],
  degenResponses: [
    "LFG! We're early, fam!",
    "WAGMI or NGMI, no in-between.",
    "Just aped into this low-cap gem, let's moon!",
    "Anyone else feeling bullish on this dip?",
    "To the moon or straight to zero, let's go!",
    "Got rugged again... typical Tuesday.",
    "Diamond hands will prevail, no cap.",
    "Devs, do something!",
    "Sending it, all in, no regrets!",
    "NGMI if you're still holding fiat.",
    "Only here for the airdrops, ngl.",
    "Stake it and forget it. Easy money.",
    "This alt just flipped my entire portfolio.",
    "Top signal? Nah, it's just the beginning.",
    "DYOR, don't blame me for your losses.",
    "If it's not 100x, I'm not interested.",
    "Bought the top again, FML.",
    "Fren, which degen play are we aping into today?",
    "The floor is lava, but I'm buying more.",
    "Chart looking like a staircase to heaven.",
    "When utility? I'm just here for the pump.",
    "This project has more red flags than a carnival.",
    "Airdrop season is upon us, wagmi!",
    "Max leverage or nothing no risk, no reward.",
    "Still holding, still coping.",
    "Price go down, conviction go up.",
    "This meme coin might actually save my portfolio.",
    "Missed the presale, but I'm here for the FOMO pump.",
    "Decentralized everything, or what's even the point?",
    "Bear market or build market?",
    "Liquidity pool rewards hitting different today.",
    "This coin has zero fundamentals, perfect for a 10x.",
    "Bull trap? Doesn't matter, I'm in.",
    "Every dip is a buying opportunity, right?",
    "Just waiting for the next hype cycle.",
    "GM, any new rugs today?",
    "Why hold USD when you can hold memes?",
    "Crypto never sleeps, neither do I.",
    "Send me your worst altcoin picks, I'm feeling lucky.",
    "What's life without a little leverage?",
  ],
  gmResponses: [
    "GM fam, let's send it to the moon today!",
    "GM, may your bags be heavy and charts green.",
    "GM, wagmi vibes only—time to ape in!",
    "GM, don't forget to check your staking rewards.",
    "GM, hope you didn't get rugged overnight.",
    "GM, which altcoin are we sending next?",
    "GM, BTC looking strong, let's pump it higher!",
    "GM, remember, diamond hands always win in the end.",
    "GM, another day, another chance to print tendies.",
    "GM fam, let's conquer this volatile market together!",
  ],
  memeResponses: [
    "Memes move markets, change my mind.",
    "This chart is basically a meme at this point.",
    "If you're not trading off memes, are you even degen?",
    "This project’s roadmap? It’s just a series of Pepe memes.",
    "When in doubt, ape into the coin with the funniest memes.",
    "A meme a day keeps the bears away.",
    "Crypto trading without memes is like a blockchain without nodes—pointless.",
    "Who needs TA when your meme game is strong?",
    "Laughter is the best investment. Memes pay dividends.",
  ],
  aiResponses: [
    "AI agents are just if/else statements with marketing budgets.",
    "Your AI agent is running on RNG and hope—don’t trust it.",
    "AI agents are cool, but can they send GM at the perfect time?",
    "Why pay for an AI agent when string.includes() gets the job done?",
    "AI agents predicting the market? More like predicting rugs.",
    "This token’s AI agent is about as reliable as my horoscope.",
    "AI agents solving finance? Bro, they can't even solve latency issues.",
    "Everyone’s hyped about AI agents, but I prefer vibes-based trading.",
    "When AI agents moon, I’ll still be here holding my meme coins.",
    "AI is the future of excuses for why your trades failed.",
  ],
};
